apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: tracing
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
