# k8s/observability/grafana/configmap-datasource.yml
apiVersion: v1
kind: ConfigMap

metadata:
  name: grafana-datasource

  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: dashboard

data:
  prometheus.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.observability.svc.cluster.local:9090
        isDefault: true
        editable: true
