# k8s/large/pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: hf-cache-large
  namespace: llm-runtime
  labels:
    app.kubernetes.io/name: hf-cache-large
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: llm-runtime
    llm.runtime/tier: large

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 250Gi
