apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-runtime

resources:
  - openai-subscription-auth-pvc.yml
  - gemini-subscription-auth-pvc.yml
  - rbac-rr-consumer.yml
  - deployment.yml
