# k8s/medium/pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: hf-cache-medium
  namespace: llm-runtime
  labels:
    app.kubernetes.io/name: hf-cache-medium
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: llm-runtime
    llm.runtime/tier: medium

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 150Gi
