# k8s/small/pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: hf-cache-small
  namespace: llm-runtime
  labels:
    app.kubernetes.io/name: hf-cache-small
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: llm-runtime
    llm.runtime/tier: small

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Gi
